spring:
  application:
    name: bet-processor
  task:
    execution:
      pool:
        core-size: 6
        max-size: 6
        queue-capacity: 8
      thread-name-prefix: BetWorker-
      shutdown:
        await-termination: true
        await-termination-period: 5m # It is a max time, if every async tasks is resolved before, it is not used

bet-processor:
  processor:
    sleeping-time: 10s